import 'package:flutter/material.dart';
import 'package:ig/singleImageView.dart';
import 'model.dart';
class DownloadPage extends StatefulWidget {
   Autogenerated user;
   DownloadPage(this.user);
  @override
  _DownloadPageState createState() => _DownloadPageState();
}

class _DownloadPageState extends State<DownloadPage> {
  
  @override
  Widget build(BuildContext context) {
    final size = MediaQuery.of(context).size;
    return Scaffold(
      appBar: AppBar(
        elevation: 0,
        backgroundColor: Colors.transparent,
      ),
      body: 
      
      GridView.builder(
          itemCount:widget.user.data.user.edgeOwnerToTimelineMedia.edges.length,
          gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount: 3,mainAxisSpacing: 2,crossAxisSpacing: 2),
          itemBuilder: (BuildContext context,int index)
          {
            return Hero(
             tag: index,
              child: GestureDetector(
                child: Container(
                
              color: Colors.yellow,
              child: Image.network(widget.user.data.user.edgeOwnerToTimelineMedia.edges[index].node.thumbnailSrc),
            ),
            onTap: ()=>Navigator.of(context).push(MaterialPageRoute(builder: (BuildContext context)=>SingleImageView(widget.user.data.user.edgeOwnerToTimelineMedia.edges[index].node.thumbnailSrc,index))),
              ),
            );
          },
        ) 
    );
  }
}