class Autogenerated {
  Data data;
  String status;

  Autogenerated({this.data, this.status});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    data = json['data'] != null ? new Data.fromJson(json['data']) : null;
    status = json['status'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.data != null) {
      data['data'] = this.data.toJson();
    }
    data['status'] = this.status;
    return data;
  }
}

class Data {
  User user;

  Data({this.user});

  Data.fromJson(Map<String, dynamic> json) {
    user = json['user'] != null ? new User.fromJson(json['user']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.user != null) {
      data['user'] = this.user.toJson();
    }
    return data;
  }
}

class User {
  EdgeOwnerToTimelineMedia edgeOwnerToTimelineMedia;

  User({this.edgeOwnerToTimelineMedia});

  User.fromJson(Map<String, dynamic> json) {
    edgeOwnerToTimelineMedia = json['edge_owner_to_timeline_media'] != null
        ? new EdgeOwnerToTimelineMedia.fromJson(
            json['edge_owner_to_timeline_media'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.edgeOwnerToTimelineMedia != null) {
      data['edge_owner_to_timeline_media'] =
          this.edgeOwnerToTimelineMedia.toJson();
    }
    return data;
  }
}

class EdgeOwnerToTimelineMedia {
  int count;
  PageInfo pageInfo;
  List<Edges> edges;

  EdgeOwnerToTimelineMedia({this.count, this.pageInfo, this.edges});

  EdgeOwnerToTimelineMedia.fromJson(Map<String, dynamic> json) {
    count = json['count'];
    pageInfo = json['page_info'] != null
        ? new PageInfo.fromJson(json['page_info'])
        : null;
    if (json['edges'] != null) {
      edges = new List<Edges>();
      json['edges'].forEach((v) {
        edges.add(new Edges.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['count'] = this.count;
    if (this.pageInfo != null) {
      data['page_info'] = this.pageInfo.toJson();
    }
    if (this.edges != null) {
      data['edges'] = this.edges.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class PageInfo {
  bool hasNextPage;
  String endCursor;

  PageInfo({this.hasNextPage, this.endCursor});

  PageInfo.fromJson(Map<String, dynamic> json) {
    hasNextPage = json['has_next_page'];
    endCursor = json['end_cursor'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['has_next_page'] = this.hasNextPage;
    data['end_cursor'] = this.endCursor;
    return data;
  }
}

class Edges {
  Node node;

  Edges({this.node});

  Edges.fromJson(Map<String, dynamic> json) {
    node = json['node'] != null ? new Node.fromJson(json['node']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.node != null) {
      data['node'] = this.node.toJson();
    }
    return data;
  }
}

class Node {
  String id;
  String sTypename;
  EdgeMediaToCaption edgeMediaToCaption;
  String shortcode;
  EdgeMediaToComment edgeMediaToComment;
  bool commentsDisabled;
  int takenAtTimestamp;
  Dimensions dimensions;
  String displayUrl;
  EdgeMediaPreviewLike edgeMediaPreviewLike;
  Owner owner;
  String thumbnailSrc;
  List<ThumbnailResources> thumbnailResources;
  bool isVideo;

  Node(
      {this.id,
      this.sTypename,
      this.edgeMediaToCaption,
      this.shortcode,
      this.edgeMediaToComment,
      this.commentsDisabled,
      this.takenAtTimestamp,
      this.dimensions,
      this.displayUrl,
      this.edgeMediaPreviewLike,
      this.owner,
      this.thumbnailSrc,
      this.thumbnailResources,
      this.isVideo});

  Node.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    sTypename = json['__typename'];
    edgeMediaToCaption = json['edge_media_to_caption'] != null
        ? new EdgeMediaToCaption.fromJson(json['edge_media_to_caption'])
        : null;
    shortcode = json['shortcode'];
    edgeMediaToComment = json['edge_media_to_comment'] != null
        ? new EdgeMediaToComment.fromJson(json['edge_media_to_comment'])
        : null;
    commentsDisabled = json['comments_disabled'];
    takenAtTimestamp = json['taken_at_timestamp'];
    dimensions = json['dimensions'] != null
        ? new Dimensions.fromJson(json['dimensions'])
        : null;
    displayUrl = json['display_url'];
    edgeMediaPreviewLike = json['edge_media_preview_like'] != null
        ? new EdgeMediaPreviewLike.fromJson(json['edge_media_preview_like'])
        : null;
    owner = json['owner'] != null ? new Owner.fromJson(json['owner']) : null;
    thumbnailSrc = json['thumbnail_src'];
    if (json['thumbnail_resources'] != null) {
      thumbnailResources = new List<ThumbnailResources>();
      json['thumbnail_resources'].forEach((v) {
        thumbnailResources.add(new ThumbnailResources.fromJson(v));
      });
    }
    isVideo = json['is_video'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['__typename'] = this.sTypename;
    if (this.edgeMediaToCaption != null) {
      data['edge_media_to_caption'] = this.edgeMediaToCaption.toJson();
    }
    data['shortcode'] = this.shortcode;
    if (this.edgeMediaToComment != null) {
      data['edge_media_to_comment'] = this.edgeMediaToComment.toJson();
    }
    data['comments_disabled'] = this.commentsDisabled;
    data['taken_at_timestamp'] = this.takenAtTimestamp;
    if (this.dimensions != null) {
      data['dimensions'] = this.dimensions.toJson();
    }
    data['display_url'] = this.displayUrl;
    if (this.edgeMediaPreviewLike != null) {
      data['edge_media_preview_like'] = this.edgeMediaPreviewLike.toJson();
    }
    if (this.owner != null) {
      data['owner'] = this.owner.toJson();
    }
    data['thumbnail_src'] = this.thumbnailSrc;
    if (this.thumbnailResources != null) {
      data['thumbnail_resources'] =
          this.thumbnailResources.map((v) => v.toJson()).toList();
    }
    data['is_video'] = this.isVideo;
    return data;
  }
}

class EdgeMediaToCaption {
  List<Edges> edges;

  EdgeMediaToCaption({this.edges});

  EdgeMediaToCaption.fromJson(Map<String, dynamic> json) {
    if (json['edges'] != null) {
      edges = new List<Edges>();
      json['edges'].forEach((v) {
        edges.add(new Edges.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.edges != null) {
      data['edges'] = this.edges.map((v) => v.toJson()).toList();
    }
    return data;
  }
}



class EdgeMediaToComment {
  int count;

  EdgeMediaToComment({this.count});

  EdgeMediaToComment.fromJson(Map<String, dynamic> json) {
    count = json['count'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['count'] = this.count;
    return data;
  }
}

class Dimensions {
  int height;
  int width;

  Dimensions({this.height, this.width});

  Dimensions.fromJson(Map<String, dynamic> json) {
    height = json['height'];
    width = json['width'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['height'] = this.height;
    data['width'] = this.width;
    return data;
  }
}

class EdgeMediaPreviewLike {
  int count;

  EdgeMediaPreviewLike({this.count});

  EdgeMediaPreviewLike.fromJson(Map<String, dynamic> json) {
    count = json['count'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['count'] = this.count;
    return data;
  }
}

class Owner {
  String id;

  Owner({this.id});

  Owner.fromJson(Map<String, dynamic> json) {
    id = json['id'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    return data;
  }
}

class ThumbnailResources {
  String src;
  int configWidth;
  int configHeight;

  ThumbnailResources({this.src, this.configWidth, this.configHeight});

  ThumbnailResources.fromJson(Map<String, dynamic> json) {
    src = json['src'];
    configWidth = json['config_width'];
    configHeight = json['config_height'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['src'] = this.src;
    data['config_width'] = this.configWidth;
    data['config_height'] = this.configHeight;
    return data;
  }
}
